create_clock -period 4.000 [get_ports -no_traverse axi_aclk]
create_generated_clock -source [get_ports sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 -4.900 -9.800} [get_ports -no_traverse int_qpll1outclk_out[0]]
create_generated_clock -source [get_ports sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 -4.900 -9.800} [get_ports -no_traverse int_qpll1outclk_out[1]]
create_generated_clock -source [get_ports sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports -no_traverse int_qpll1outrefclk_out[0]]
create_generated_clock -source [get_ports sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports -no_traverse int_qpll1outrefclk_out[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxn[7]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_rxp[7]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txn[7]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet pci_exp_txp[7]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.000 [get_ports -no_traverse -quiet axi_aclk]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 10.000 [get_ports -no_traverse -quiet sys_clk]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 10.000 [get_ports -no_traverse -quiet sys_clk_gt]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet axi_aclk]]
