set_property PACKAGE_PIN AP8 [get_ports LED_0]
set_property PACKAGE_PIN H23 [get_ports LED_1]
set_property PACKAGE_PIN P20 [get_ports LED_2]
set_property PACKAGE_PIN P21 [get_ports LED_3]
set_property PACKAGE_PIN AE8 [get_ports SW_E]
set_property PACKAGE_PIN AD10 [get_ports SW_N]
set_property PACKAGE_PIN AF8 [get_ports SW_S]
set_property PACKAGE_PIN AF9 [get_ports SW_W]

set_property IOSTANDARD LVCMOS18 [get_ports LED_1]
set_property IOSTANDARD LVCMOS18 [get_ports LED_2]
set_property IOSTANDARD LVCMOS18 [get_ports LED_3]
set_property IOSTANDARD LVCMOS18 [get_ports SW_N]
set_property IOSTANDARD LVCMOS18 [get_ports SW_E]
set_property IOSTANDARD LVCMOS18 [get_ports SW_S]
set_property IOSTANDARD LVCMOS18 [get_ports SW_W]
set_property IOSTANDARD LVCMOS18 [get_ports LED_0]
