# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/design_1_xdma_0_1.xci
# IP: The module: 'design_1_xdma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_1/xdma_v4_1_4_blk_mem_64_reg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/design_1_xdma_0_1_pcie3_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip} -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/ip_0/design_1_xdma_0_1_pcie3_ip_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip_gt || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip_gt} -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/ip_0/synth/design_1_xdma_0_1_pcie3_ip_gt_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/ip_0/synth/design_1_xdma_0_1_pcie3_ip_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip_gt || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/source/design_1_xdma_0_1_pcie3_ip-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/synth/design_1_xdma_0_1_pcie3_ip_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/design_1_xdma_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xdma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/source/design_1_xdma_0_1_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/synth/design_1_xdma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/design_1_xdma_0_1.xci
# IP: The module: 'design_1_xdma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_1/xdma_v4_1_4_blk_mem_64_reg_be.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/design_1_xdma_0_1_pcie3_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip} -quiet] -quiet

# IP: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/ip_0/design_1_xdma_0_1_pcie3_ip_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip_gt || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip_gt} -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/ip_0/synth/design_1_xdma_0_1_pcie3_ip_gt_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/ip_0/synth/design_1_xdma_0_1_pcie3_ip_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip_gt || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/source/design_1_xdma_0_1_pcie3_ip-PCIE_X0Y0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_1_pcie3_ip || ORIG_REF_NAME==design_1_xdma_0_1_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/ip_0/synth/design_1_xdma_0_1_pcie3_ip_ooc.xdc

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/design_1_xdma_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/source/design_1_xdma_0_1_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_1/synth/design_1_xdma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
