# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-27894-desktop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcku040-ffva1156-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map
    /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top
    /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal
  } {
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/phy/design_1_ddr4_0_0_phy_ddr4.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/ip_top/design_1_ddr4_0_0_phy.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_wtr.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ref.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_rd_wr.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_periodic.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_group.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ctl.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_p.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_c.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_a.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_timer.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_rank.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_wr_data.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_rd_data.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_cmd.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_ar_channel.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_aw_channel.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_b_channel.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_fifo.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_r_channel.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_w_channel.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_a_upsizer.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_register_slice.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_upsizer.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axic_register_slice.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_and.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_and.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_or.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_or.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_command_fifo.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel_static.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_r_upsizer.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_w_upsizer.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/clocking/ddr4_v2_2_infrastructure.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_write.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_byte.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_bit.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_sync.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_read.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_rd_en.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_pi.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_mc_odt.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx_data.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_config_rom.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_addr_decode.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_top.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_dp_AB9.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top/design_1_ddr4_0_0.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top/design_1_ddr4_0_0_ddr4.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top/design_1_ddr4_0_0_ddr4_mem_intfc.sv
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/design_1_ddr4_0_0_ddr4_cal_riu.sv
      /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map
    /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top
    /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal
  } {
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/synth/bd_45eb.v
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_0/synth/design_1_ddr4_0_0_microblaze_mcs.v
    }
      rt::read_vhdl -lib microblaze_v11_0_2 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/f871/hdl/microblaze_v11_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/synth/bd_45eb_microblaze_I_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_1/synth/bd_45eb_rst_0_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_2/synth/bd_45eb_ilmb_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_3/synth/bd_45eb_dlmb_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_4/synth/bd_45eb_dlmb_cntlr_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_5/synth/bd_45eb_ilmb_cntlr_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_6/synth/bd_45eb_lmb_bram_I_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_7/synth/bd_45eb_second_dlmb_cntlr_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_8/synth/bd_45eb_second_ilmb_cntlr_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_9/synth/bd_45eb_second_lmb_bram_I_0.vhd
      /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_10/synth/bd_45eb_iomodule_0_0.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_v10_v3_0_10 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/2e88/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_17 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/db6f/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib iomodule_v3_1_5 /home/luke/Documents/Capstone/FPGA_API/vivado_designs/DMA_2/DMA_2.srcs/sources_1/bd/design_1/ipshared/f748/hdl/iomodule_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-27894-desktop/realtime/design_1_ddr4_0_0_synth.xdc
    rt::sdcChecksum
    set rt::top design_1_ddr4_0_0
    rt::set_parameter enableIncremental true
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-27894-desktop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
